controller_manager:
  ros__parameters:

    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ft_sensor_bd:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

ft_sensor_bd:
  ros__parameters:
    sensor_name: ft_sensor
    frame_id: lower_arm

arm_controller:
  ros__parameters:
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    command_interfaces:
      - position
    state_interfaces:
      - position